# Generated by Django 5.0.6 on 2024-06-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='selfinfo',
            name='code',
        ),
    ]
