# Generated by Django 5.0.6 on 2024-06-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_invoiceinfo_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='amount',
        ),
    ]
