# Generated by Django 5.0.6 on 2024-06-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_entry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='challan',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ChallanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=64)),
                ('shade', models.CharField(max_length=64)),
                ('dyeingType', models.CharField(blank=True, max_length=64, null=True)),
                ('befQty', models.FloatField(blank=True, null=True)),
                ('aftQty', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
                ('challanNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanEntry', to='manager.challan')),
            ],
        ),
    ]
